import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import cn from 'classnames'

const montserrat = Montserrat({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Hoef Entertainment',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          montserrat.className,
          'flex min-h-screen flex-col bg-slate-950 antialiased'
        )}
      >
        {children}
      </body>
    </html>
  )
}
